# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: |
    cat <<EOF > eua.config
    apiKey=4384ec56c4df4888a0465b48aeac0075c514ebd76b704630938e7dae0980f122
    productName=PepsiPOC
    projectName=WebGoat_2.0
    enableImpactAnalysis=true
    requireKnownSha1=false
    resolveAllDependencies=false
    maven.resolveDependencies=true
    maven.aggregateModules=true
    fileSystemScan=false
    EOF
    cat eua.config
    echo config created successfully
    curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
    curl -o xModuleAnalyzer.jar https://unified-agent.s3.amazonaws.com/xModuleAnalyzer/xModuleAnalyzer-21.4.1.jar
    echo UA downloaded successfully
    java -jar wss-unified-agent.jar -d ./ -analyzeMultiModule multimodule.txt -project WebGoat_2.0 -product PepsiPOC -apiKey 4384ec56c4df4888a0465b48aeac0075c514ebd76b704630938e7dae0980f122
    #sed -i 's/AppPath4=/AppPath4=\/webgoat-server\/target\/webgoat-server-v8.0.0.jar/1' multimodule.txt
    #echo 'multimodule.txt contents'
    cat multimodule.txt
    #java -jar xModuleAnalyzer.jar -xModulePath multimodule.txt -fsaJarPath ./wss-unified-agent.jar -c ./eua.config -aggregateModules true
  displayName: 'xModuleAnalyzer & UA download an run'

